// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delete_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteChirp = `-- name: DeleteChirp :exec
DELETE FROM chirps
where user_id = $1 and id = $2
`

type DeleteChirpParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteChirp(ctx context.Context, arg DeleteChirpParams) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, arg.UserID, arg.ID)
	return err
}
