// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_refresh_token.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getRefreshToken = `-- name: GetRefreshToken :one
select token, refresh_tokens.created_at, refresh_tokens.updated_at, expires_at, revoked_at, user_id, id, users.created_at, users.updated_at, email, hashed_password from refresh_tokens 
join users on users.id = refresh_tokens.user_id
where token = $1
    AND expires_at > NOW()
    and revoked_at is null
`

type GetRefreshTokenRow struct {
	Token          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	ExpiresAt      sql.NullTime
	RevokedAt      sql.NullTime
	UserID         uuid.NullUUID
	ID             uuid.UUID
	CreatedAt_2    time.Time
	UpdatedAt_2    time.Time
	Email          string
	HashedPassword string
}

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, token)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserID,
		&i.ID,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}
